### ISSUE TITLE
Plans for Bikesliprun and Bnmode?

### ISSUE THREAD

**Issue by henderkes** [Dabomstew/pokered-speedchoice#2]
^ title

**Comment by Dabomstew** [comment]
bikesliprun: fast movement in general in some form yes, the exact way bikesliprun worked in fastmenu no (lucky changed a lot of movement code to implement BSR and a lot of its "features" were caused by bugs)
bnmode (fast resets I think?): maybe, but it can have some negative effects on optimal strats, namely making scumming for a low probability event a lot more appealing

**Comment by henderkes** [comment]
Oh yeah I agree that luckys Implementation broke a few things and had funny effects on pushing boulders, cutscenes and dsum. It's just a very major time loss to walk very slowly the entire time, running shoes would make it far more appealing for bingos and 151's.

Bnmode was instant reset, yeah. I think what lucky did to prevent abusing it for low probability events was having an internal counter and after 10 resets in a short amount of time you are punished with normal resetting for the next 10 minutes.

**Comment by Dabomstew** [comment]
Agreed that walking is annoying. See #7 for current plans.

Bnmode I will consider further, not going to commit to adding it just yet.
